In [2]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib as mp
from sklearn.linear_model import LinearRegression

In [3]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [3]:
data=pd.read_csv('E:/Own Practice/car data.csv')

In [4]:
data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [12]:
data

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [6]:
data.tail()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
296     city  2016           9.50           11.6       33988    Diesel   
297     brio  2015           4.00            5.9       60000    Petrol   
298     city  2009           3.35           11.0       87934    Petrol   
299     city  2017          11.50           12.5        9000    Diesel   
300     brio  2016           5.30            5.9        5464    Petrol   

    Seller_Type Transmission  Owner  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0

In [7]:
data.isnull()

Car_Name   Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0       False  False          False          False       False      False   
1       False  False          False          False       False      False   
2       False  False          False          False       False      False   
3       False  False          False          False       False      False   
4       False  False          False          False       False      False   
..        ...    ...            ...            ...         ...        ...   
296     False  False          False          False       False      False   
297     False  False          False          False       False      False   
298     False  False          False          False       False      False   
299     False  False          False          False       False      False   
300     False  False          False          False       False      False   

     Seller_Type  Transmission  Owner  
0          False         False  False  
1          False         False  False  
2          False         False  False  
3          False         False  False  
4          False         False  False  
..           ...           ...    ...  
296        False         False  False  
297        False         False  False  
298        False         False  False  
299        False         False  False  
300        False         False  False  

[301 rows x 9 columns]

In [8]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [39]:
reg=LinearRegression()
reg.fit(data[['Selling_Price']],data['Kms_Driven'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
reg.predict([[20]])

array([40372.34826729])

In [41]:
# reg.fit(data['Present_Price'],data['Kms_Driven'])

In [42]:
reg.predict([[35]])

array([43721.85766783])

In [43]:
reg.predict([[51]])

array([47294.66769508])

In [44]:
#multiple regression

In [45]:
reg.coef_

array([223.3006267])

In [46]:
reg.intercept_

35906.335733238164

In [47]:
pred=223.3006267*130-35906.335733238164

In [48]:
print(pred)

-6877.2542622381625


In [49]:
from sklearn.metrics import r2_score

In [54]:
data

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [57]:
pred_val=reg.predict([[40],[6800]])

In [58]:
print(pred_val)

[  44838.36080135 1554350.59731203]


In [59]:
error=r2_score([[40],[6800]],pred_val)

In [60]:
print(error)

-104902.52860418524


In [62]:
from sklearn.metrics import mean_absolute_error
error1=mean_absolute_error([[45],[5000]],pred_val)
print(error1)

797071.9790566892


In [66]:
from sklearn.metrics import mean_squared_error
sqr=mean_squared_error([[45],[5000]],pred_val)

In [67]:
print(sqr)

1201246859281.5115


In [72]:
Data_1=pd.read_csv('E:/Own Practice/car data.csv')

In [74]:
Data_1

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [76]:
Data_1.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [78]:
Data_1.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [79]:
X=Data_1[['Kms_Driven','Year','Selling_Price']]
Y=Data_1['Present_Price']

In [83]:
X.head()

Kms_Driven  Year  Selling_Price
0       27000  2014           3.35
1       43000  2013           4.75
2        6900  2017           7.25
3        5200  2011           2.85
4       42450  2014           4.60

In [82]:
Y.head()

0    5.59
1    9.54
2    9.85
3    4.15
4    6.87
Name: Present_Price, dtype: float64

In [84]:
m_reg=LinearRegression()

In [85]:
m_reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [86]:
m_reg.coef_

array([ 1.09336596e-05, -7.25067165e-01,  1.58980972e+00])

In [87]:
m_reg.intercept_

1459.8294086928938

In [88]:
m_reg.predict([[27000,2014,3.35]])

array([5.16520934])

In [89]:
m_reg.predict([[62200,2015,3.01]])

array([4.28447169])

In [90]:
m_reg.predict([[110000,2015,6.26]])

array([9.97398222])

In [94]:
m_reg.predict([[11000,2016,1.2]])

array([0.12204555])

In [95]:
import pickle

In [97]:
with open ('E:/my_models',"wb") as f:
    pickle.dump(m_reg,f)