In [1]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression

In [8]:
ds= pd.read_csv(r'E:/DataSet-Salary.csv')

In [9]:
ds

exp  salary
0    1.1   39343
1    1.3   46205
2    1.5   37731
3    2.0   43525
4    2.2   39891
5    2.9   56642
6    3.0   60150
7    3.2   54445
8    3.2   64445
9    3.7   57189
10   3.9   63218
11   4.0   55794
12   4.0   56957
13   4.1   57081
14   4.5   61111
15   4.9   67938
16   5.1   66029
17   5.3   83088
18   5.9   81363
19   6.0   93940
20   6.8   91738
21   7.1   98273
22   7.9  101302
23   8.2  113812
24   8.7  109431
25   9.0  105582
26   9.5  116969
27   9.6  112635
28  10.3  122391
29  10.5  121872

In [10]:
ds.isnull().sum()

exp       0
salary    0
dtype: int64

In [11]:
reg=LinearRegression()

In [12]:
reg.fit(ds[['exp']],ds['salary'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
reg.predict([[11]])

array([129741.78573467])

In [15]:
reg.predict([[15]])

array([167541.63502049])

In [16]:
reg.coef_

array([9449.96232146])

In [17]:
reg.intercept_

25792.20019866871

In [18]:
pred=9449.96232146*11 -25792.20019866871
print(pred)

78157.38533739129
